export const EMPLOYEE_EXAMS_PAGE_SIZE = 8;

export const EMPLOYEE_EXAMS_FILTER_DEBOUNCE_MS = 400;

export const EMPLOYEE_EXAMS_FILTER_OPTIONS_PAGE_SIZE = 100;

export const EMPLOYEE_EXAMS_REPORT_PAGE_SIZE = 100;
